version: '3.8'

services:
  php:
    build:
      context: ./php
    container_name: peligro-wordpress-app
    restart: always
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - custom_network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/html
    depends_on:
      - php
    networks:
      - custom_network


networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.42.12.0/28
          gateway: 172.42.12.1